### ISSUE TITLE
grpclib 0.3.2 unhelpful error with bad header value

### ISSUE THREAD

**Issue by danielgtaylor-isp** [vmagamedov/grpclib#113]
When upgrading from grpclib 0.3.1 to 0.3.2 we experienced an issue where one of our headers had a bad value ending with `\n` and the error message was not useful, requiring a lot of time to debug. Example:

```py
Traceback (most recent call last):
  File "/home/example/.venv/lib/python3.7/site-packages/grpclib/client.py", line 360, in recv_initial_metadata
    headers = await self._stream.recv_headers()
  File "/home/example/.venv/lib/python3.7/site-packages/grpclib/protocol.py", line 349, in recv_headers
    await self.headers_received.wait()
  File "/home/example/.pyenv/versions/3.7.7/lib/python3.7/asyncio/locks.py", line 293, in wait
    await fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/example/.pyenv/versions/3.7.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "<stdin>", line 4, in ls
  File "/home/example/.venv/lib/python3.7/site-packages/grpclib/client.py", line 830, in __call__
    reply = await stream.recv_message()
  File "/home/example/.venv/lib/python3.7/site-packages/grpclib/client.py", line 408, in recv_message
    await self.recv_initial_metadata()
  File "/home/example/.venv/lib/python3.7/site-packages/grpclib/client.py", line 380, in recv_initial_metadata
    self.initial_metadata = im
  File "/home/example/.venv/lib/python3.7/site-packages/grpclib/utils.py", line 70, in __exit__
    raise self._error
grpclib.exceptions.StreamTerminatedError: Stream reset by remote party, error_code: 1
```

This is generated using code like this:

```py
async def _add_auth(event: SendRequest) -> None:
    """Add user/key to the request headers of every outgoing request."""
    event.metadata["user"] = USER_VALUE
    event.metadata["key"] = SECRET_VALUE

listen(grpc_channel, SendRequest, _add_auth)
```

In our case, the bug was that `SECRET_VALUE` ended in a `\n` which was a configuration mistake. As soon as we found the problem, we were able to get a better error like this:

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/example/.pyenv/versions/3.7.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "<stdin>", line 4, in ls
  File "/home/example/.venv/lib/python3.7/site-packages/grpclib/client.py", line 830, in __call__
    reply = await stream.recv_message()
  File "/home/example/.venv/lib/python3.7/site-packages/grpclib/client.py", line 408, in recv_message
    await self.recv_initial_metadata()
  File "/home/example/.venv/lib/python3.7/site-packages/grpclib/client.py", line 376, in recv_initial_metadata
    self._raise_for_grpc_status(headers_map)
  File "/home/example/.venv/lib/python3.7/site-packages/grpclib/client.py", line 337, in _raise_for_grpc_status
    raise GRPCError(status, message, details)
grpclib.exceptions.GRPCError: (<Status.UNAUTHENTICATED: 16>, 'request failed, invalid request metadata/auth', None)
```

And when passing the proper secret value the request now works.

It looks like this code was changed in https://github.com/vmagamedov/grpclib/commit/d2ff0029ab8e104e17052ddda27c21be7b25b4c5#diff-1e1ecaa37b653c7027d817b6c287965cR593-R596 for efficiency, and I'm not opposed to that change, but it would be nice to get some better error message. This issue wasted a **lot** of time for us unfortunately.

**Comment by vmagamedov** [comment]
Sorry for that backward-incompatible change. Now I'm trying to find a proper solution for this case. I have to find a source of truth describing how we should normalise/validate metadata values. `h2` library silently strips whitespace, `grpcio` library raises cryptic error together with a log message like this:
```
E0625 17:48:07.146573000 4808285632 call.cc:911]                       validate_metadata: {"created":"@1593096487.146562000","description":"Illegal header value","file":"src/core/lib/surface/validate_metadata.cc","file_line":44,"offset":3,"raw_bytes":"62 61 72 0a 'bar.'\u0000"}
```

**Comment by vmagamedov** [comment]
Turns out that the problem is that I'm using `re.match` instead of `re.fullmatch` to validate a metadata value. And the change in `0.3.2` release you mentioned above just made this bug visible.
