### ISSUE TITLE
Installation via pip results in import error

### ISSUE THREAD

**Issue by mk-fg** [vmagamedov/grpclib#119]
Hi,

Currently, using "pip3 install grpclib protobuf" as suggested in the README results in installing h2-4.0.0 as a dependency, which seem to be incompatible with current grpclib version:

```
% pip3 install --user grpclib protobuf
Collecting grpclib
  Using cached grpclib-0.4.0.tar.gz (57 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting protobuf
  Downloading protobuf-3.13.0-cp38-cp38-manylinux1_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 489 kB/s
Collecting h2
  Using cached h2-4.0.0-py3-none-any.whl (57 kB)
Collecting multidict
  Using cached multidict-4.7.6-cp38-cp38-manylinux1_x86_64.whl (162 kB)
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (from protobuf) (50.3.0)
Requirement already satisfied: six>=1.9 in /usr/lib/python3.8/site-packages (from protobuf) (1.15.0)
Collecting hyperframe<7,>=6.0
  Downloading hyperframe-6.0.0-py3-none-any.whl (11 kB)
Collecting hpack<5,>=4.0
  Downloading hpack-4.0.0-py3-none-any.whl (32 kB)
Building wheels for collected packages: grpclib
  Building wheel for grpclib (PEP 517) ... done
  Created wheel for grpclib: filename=grpclib-0.4.0-py3-none-any.whl size=69874 sha256=9c0bc728cdfb25945bf10d6918594ccb9deca62d800bee65792c91ec8526908a
  Stored in directory: /home/mk-fg/.cache/pip/wheels/fb/52/3d/0f357bf3d9fd4046eb2cb1bdc7754a6ec0f7629b726d7a537d
Successfully built grpclib
Installing collected packages: hyperframe, hpack, h2, multidict, grpclib, protobuf
  WARNING: The scripts protoc-gen-grpclib_python and protoc-gen-python_grpc are installed in '/home/mk-fg/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed grpclib-0.4.0 h2-4.0.0 hpack-4.0.0 hyperframe-6.0.0 multidict-4.7.6 protobuf-3.13.0

% python3 -c 'import grpclib.client'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mk-fg/.local/lib/python3.8/site-packages/grpclib/client.py", line 26, in <module>
    from .protocol import H2Protocol, AbstractHandler, Stream as _Stream, Peer
  File "/home/mk-fg/.local/lib/python3.8/site-packages/grpclib/protocol.py", line 22, in <module>
    from h2.events import StreamReset, PriorityUpdated, PingAcknowledged
ImportError: cannot import name 'PingAcknowledged' from 'h2.events' (/home/mk-fg/.local/lib/python3.8/site-packages/h2/events.py)
```

I suppose this is what should occasionally happen with non-versioned dependencies, as they are currently specified in setup.cfg, so not entirely sure if it's a problem with setup.cfg, README suggesting somewhat error-prone installation path, or just an expected transient breakage.

Thought to report it, in case it's not an already known issue.

Thanks!

**Comment by vmagamedov** [comment]
Thanks for your report, this is new to me.

**Comment by vmagamedov** [comment]
`grpclib==0.4.1` with a fix is ready to use
