### ISSUE TITLE
"ModuleNotFoundError: No module named 'pbr'" on install

### ISSUE THREAD

**Issue by n00bsys0p** [vmagamedov/grpclib#120]
Hi,

On versions >=0.4.0, I'm getting an error during install relating to the module "pbr". I do have this module installed, and have tested the line of code which is causing the error, which appears to work fine in a slightly contrived context as shown in the below text. Full error included at the end.

```
$ python
Python 3.8.5 (default, Aug 16 2020, 17:44:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> __import__('pbr', fromlist=['__name__'], level=0)
<module 'pbr' from '/home/user/.pyenv/versions/project/lib/python3.8/site-packages/pbr/__init__.py'>
```

```
$ pip install -U grpclib --ignore-installed --no-cache
Collecting grpclib
  Downloading grpclib-0.4.1.tar.gz (57 kB)
     |████████████████████████████████| 57 kB 692 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/.pyenv/versions/3.8.5/envs/project/bin/python3.8 /home/user/.pyenv/versions/3.8.5/envs/project/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpgcws3rws
       cwd: /tmp/pip-install-2xmwencb/grpclib
  Complete output (34 lines):
  running egg_info
  writing grpclib.egg-info/PKG-INFO
  writing dependency_links to grpclib.egg-info/dependency_links.txt
  writing entry points to grpclib.egg-info/entry_points.txt
  writing requirements to grpclib.egg-info/requires.txt
  writing top-level names to grpclib.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/home/user/.pyenv/versions/3.8.5/envs/project/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/user/.pyenv/versions/3.8.5/envs/project/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/user/.pyenv/versions/3.8.5/envs/project/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-b003fdk4/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-b003fdk4/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-b003fdk4/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 3, in <module>
      setuptools.setup()
    File "/tmp/pip-build-env-b003fdk4/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/user/.pyenv/versions/3.8.5/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/user/.pyenv/versions/3.8.5/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/user/.pyenv/versions/3.8.5/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-b003fdk4/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 285, in run
      writer = ep.resolve()
    File "/home/user/.pyenv/versions/3.8.5/envs/project/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2478, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
  ModuleNotFoundError: No module named 'pbr'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/user/.pyenv/versions/3.8.5/envs/project/bin/python3.8 /home/user/.pyenv/versions/3.8.5/envs/project/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpgcws3rws Check the logs for full command output.
```

**Comment by vmagamedov** [comment]
I've tried to install `grpclib` into an environment with a latest `pbr` library installed before and have no errors. Can you provide more info about your environment? Which versions of setuptools/pip/pbr do you have? Can you try to install grpclib into a fresh virtualenv?

Maybe you can figure out what is wrong with `grpclib`? The only change I think of is that now I'm using version constrains in setup.cfg to specify h2 version more precisely: https://github.com/vmagamedov/grpclib/blob/bb9f450ab2e7499a2e5565f65ee454e7fa637878/setup.cfg#L27-L28

**Comment by vmagamedov** [comment]
And to be clear `grpclib` is not using `pbr`. It is `pbr` affects how `grpclib` is getting installed in some strange ways.

**Comment by n00bsys0p** [comment]
Ok - so first up, apologies for the trouble in advance. Uinstalling and reinstalling my pyenv venv from scratch has resolved the problem.

The package in my project which brings in pbr is [bandit](https://github.com/PyCQA/bandit), so I guess an old version of either of these must have been causing the error.

Thanks for your time!
