### ISSUE TITLE
Handle asyncio.CancelledError in server methods

### ISSUE THREAD

**Issue by tamirOK** [vmagamedov/grpclib#122]
I have such `client.py`:
```python
import asyncio

from grpclib.client import Channel

# generated by protoc
from helloworld_pb2 import HelloRequest
from helloworld_grpc import GreeterStub


async def main() -> None:
    async with Channel('127.0.0.1', 50051) as channel:
        greeter = GreeterStub(channel)

        try:
            await asyncio.wait_for(
                greeter.SayHello(HelloRequest(name='Dr. Strange')),
                2,
            )
        except asyncio.TimeoutError:
            print('Too slow operation')
        else:
            print("Client is OK")


if __name__ == '__main__':
    asyncio.run(main())
```
And `server.py`:
```python
import asyncio
import time

import grpclib.server
from grpclib.utils import graceful_exit
from grpclib.server import Server, Stream

# generated by protoc
from helloworld_pb2 import HelloRequest, HelloReply
from helloworld_grpc import GreeterBase


class Greeter(GreeterBase):

    def sync_op(self):
        time.sleep(20)

    async def SayHello(self, stream: Stream[HelloRequest, HelloReply]) -> None:
        request = await stream.recv_message()

        loop = asyncio.get_event_loop()

        try:
            # Running slow sync operation in separate thread here
            await loop.run_in_executor(None, self.sync_op)
        except asyncio.CancelledError:
            # Try to raise exception for this case
            raise grpclib.exceptions.GRPCError(
                grpclib.const.Status.INTERNAL,
                'FAILED',
            )
        except Exception:
            raise grpclib.exceptions.GRPCError(
                grpclib.const.Status.UNAVAILABLE,
                'UNAVAILABLE',
            )
        
        message = f'Hello, {request.name}!'
        await stream.send_message(HelloReply(message=message))


async def main(*, host: str = '127.0.0.1', port: int = 50051) -> None:
    server = Server([Greeter()])
    with graceful_exit([server]):
        # Note: graceful_exit isn't supported in Windows
        await server.start(host, port)
        print(f'Serving on {host}:{port}')
        await server.wait_closed()


if __name__ == '__main__':
    asyncio.run(main())
```

When I run `client.py`, I got such exception on server side:
```
Failed to handle cancellation
Traceback (most recent call last):
  File "server.py", line 24, in SayHello
    await loop.run_in_executor(None, self.sync_op)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tamirok/Documents/python/ideas/grpclib/.venv/lib/python3.8/site-packages/grpclib/server.py", line 440, in request_handler
    await method_func(stream)
  File "server.py", line 26, in SayHello
    raise grpclib.exceptions.GRPCError(
grpclib.exceptions.GRPCError: (<Status.INTERNAL: 13>, 'FAILED', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tamirok/Documents/python/ideas/grpclib/.venv/lib/python3.8/site-packages/grpclib/server.py", line 440, in request_handler
    await method_func(stream)
  File "/home/tamirok/Documents/python/ideas/grpclib/.venv/lib/python3.8/site-packages/grpclib/utils.py", line 70, in __exit__
    raise self._error
grpclib.exceptions.StreamTerminatedError: Stream reset by remote party, error_code: 0
```
However if I don't handle `asyncio.CancelledError`, there will be no exception on server side. 
Is it possible to raise custom exception in this case without getting error?

I am running `Python 3.8.0` with `grpclib==0.4.1`

**Comment by vmagamedov** [comment]
`Stream reset by remote party` means that HTTP/2 stream (request) is already closed (by the client) and there is no way to return anything to the client in this case. So the client won't receive your `GRPCError(Status.INTERNAL, 'FAILED')`.

So generally there is no need to catch `CancelledError` and re-raise another exception.

`grpclib` raises an error `Failed to handle cancellation` because it thinks that this is a bug in your code. The best way to deal with `CancelledError` is to catch it with a try..finally or re-raise an original exception this way:
```python
try:
    await loop.run_in_executor(None, self.sync_op)
except asyncio.CancelledError as exc:
    # do something with exc
    raise
```
Here is a corresponding documentation: https://grpclib.readthedocs.io/en/latest/errors.html#server-side, maybe you can suggest how to improve it.

**Comment by vmagamedov** [comment]
@tamirOK are you ok to close this issue?

**Comment by tamirOK** [comment]
Yes, thank you!
