### ISSUE TITLE
'H2Connection' object has no attribute '_frame_dispatch_table'

### ISSUE THREAD

**Issue by haf** [vmagamedov/grpclib#140]
```
common/io_cdk/api_test.py:174:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
common/io_cdk/api_test.py:97: in create_connector_rpc_server
    async for m in validate():
common/io_cdk/api_test.py:81: in validate
    listen(channel, RecvRequest, set_server_span_factory(server_logger))
/Users/h/.local/share/virtualenvs/io-005dV5B7/lib/python3.9/site-packages/grpclib/events.py:121: in listen
    target.__dispatch__.add_listener(event_type, callback)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <grpclib.events._DispatchChannelEvents object at 0x106f47b80>, event_type = <class 'grpclib.events.RecvRequest'>
callback = <function set_server_span_factory.<locals>.set_server_span at 0x106f328b0>

    def add_listener(
        self,
        event_type: Type[_Event],
        callback: _Callback,
    ) -> None:
>       self.__dict__.pop(self.__dispatch_methods__[event_type], None)
E       KeyError: <class 'grpclib.events.RecvRequest'>

/Users/h/.local/share/virtualenvs/io-005dV5B7/lib/python3.9/site-packages/grpclib/events.py:78: KeyError
------------------------------------------------------------------- Captured log call -------------------------------------------------------------------
ERROR    asyncio:base_events.py:1738 Exception in callback H2Protocol.data_received(b'PRI * HTTP/...\x00@\x00\x00')
handle: <Handle H2Protocol.data_received(b'PRI * HTTP/...\x00@\x00\x00')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/h/.local/share/virtualenvs/io-005dV5B7/lib/python3.9/site-packages/grpclib/protocol.py", line 712, in data_received
    events = self.connection.feed(data)
  File "/Users/h/.local/share/virtualenvs/io-005dV5B7/lib/python3.9/site-packages/grpclib/protocol.py", line 189, in feed
    return self._connection.receive_data(data)  # type: ignore
  File "/Users/h/.local/share/virtualenvs/io-005dV5B7/lib/python3.9/site-packages/h2/connection.py", line 1463, in receive_data
    events.extend(self._receive_frame(frame))
  File "/Users/h/.local/share/virtualenvs/io-005dV5B7/lib/python3.9/site-packages/h2/connection.py", line 1486, in _receive_frame
    frames, events = self._frame_dispatch_table[frame.__class__](frame)
AttributeError: 'H2Connection' object has no attribute '_frame_dispatch_table'
ERROR    asyncio:base_events.py:1738 Exception in callback H2Protocol.data_received(b'\x00\x00*\x...\x00@\x00\x00')
handle: <Handle H2Protocol.data_received(b'\x00\x00*\x...\x00@\x00\x00')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/h/.local/share/virtualenvs/io-005dV5B7/lib/python3.9/site-packages/grpclib/protocol.py", line 712, in data_received
    events = self.connection.feed(data)
  File "/Users/h/.local/share/virtualenvs/io-005dV5B7/lib/python3.9/site-packages/grpclib/protocol.py", line 189, in feed
    return self._connection.receive_data(data)  # type: ignore
  File "/Users/h/.local/share/virtualenvs/io-005dV5B7/lib/python3.9/site-packages/h2/connection.py", line 1463, in receive_data
    events.extend(self._receive_frame(frame))
  File "/Users/h/.local/share/virtualenvs/io-005dV5B7/lib/python3.9/site-packages/h2/connection.py", line 1486, in _receive_frame
    frames, events = self._frame_dispatch_table[frame.__class__](frame)
AttributeError: 'H2Connection' object has no attribute '_frame_dispatch_table'
=================================================================== warnings summary ====================================================================
common/io_cdk/api_test.py::test_get_spec[test_input0-expected0]
  /Users/h/.local/share/virtualenvs/io-005dV5B7/lib/python3.9/site-packages/grpclib/server.py:732: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
    await asyncio.wait({h.wait_closed() for h in self._handlers})
```

Not quite sure what might be causing this. I've re-generated the proto files multiple times and I'm not doing anything particular to the python path.

Calling code

```python
    async def exchange_authz_code() -> Union[c.ExchangeAuthzCodeResult, shared.LogMessage]:
        """Test exchanging authz code."""
        req = msg.ExchangeAuthzCodeRequest(instance_id="lg_sc_42", authz_code=authz_code, access_token_vars={})
        async with ChannelFor([server]) as channel:
            listen(channel, RecvRequest, set_server_span_factory(server_logger))
            listen(channel, SendTrailingMetadata, end_server_span)
            async with ConnectorStub(channel).ExchangeAuthzCode.open() as opened_stream:
                await opened_stream.send_message(req, end=True)
                async for resp in opened_stream:
                    return resp
```

Versions:
- python 3.9.6
- grpclib 0.4.1

**Comment by vmagamedov** [comment]
`RecvRequest` and `SendTrailingMetadata` events are server events and should be listened on the server instance, not on the channel.

`ChannelFor` hides its server implementation, but to test that everything works you can use `channel._server` attribute (only for testing purposes).

```python
async with ChannelFor([server]) as channel:
    listen(channel._server, RecvRequest, set_server_span_factory(server_logger))
    listen(channel._server, SendTrailingMetadata, end_server_span)
```

And you using old grpclib version, you can install latest release candidate like this:
```console
$ pip install --pre grpclib
```

**Comment by vmagamedov** [comment]
Updated previous comment

**Comment by haf** [comment]
Thank you!

**Comment by haf** [comment]
Will try ASAP https://github.com/pypa/pipenv/issues/4769

**Comment by haf** [comment]
Works well.

**Comment by jbkoh** [comment]
@vmagamedov Hi, thanks for the useful hint! I have the same needs to test a method with a listener, but it seems `channel_for._server` doesn't exist for the recent version of grpclib (0.4.3rc3). Do you know how to do the same thing with the current version? Thanks in advance.

**Comment by jbkoh** [comment]
Nvm, I was using `channel._server` than `channel_for._server`. Thanks!
