### ISSUE TITLE
exception: KeyError: <class 'h2.events.PingReceived'>

### ISSUE THREAD

**Issue by x1m** [vmagamedov/grpclib#55]
Hey, thanks for this awesome lib!

My server is suddenly raising an exception. No other requests can be processed.
Not sure when and where this came from.. cannot reproduce this exception.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpclib/protocol.py", line 407, in process
    proc = self.processors[event.__class__]
KeyError: <class 'h2.events.PingReceived'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 813, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.7/site-packages/grpclib/protocol.py", line 509, in data_received
    self.processor.process(event)
  File "/usr/local/lib/python3.7/site-packages/grpclib/protocol.py", line 409, in process
    raise NotImplementedError(event)
NotImplementedError: <PingReceived ping_data:02041010090e0707>
```

I use:
Python 3.7.2
grpclib==0.2.1
4.14.65+ x86_64 GNU/Linux Debian 9.6

Does the **0.2.2rc** version of the library fix the issue?

**Comment by x1m** [comment]
exception message:
```
Fatal error: protocol.data_received() call failed.
protocol: <grpclib.protocol.H2Protocol object at 0x7f844f6294e0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
```

**Comment by edigaryev** [comment]
>Does the 0.2.2rc version of the library fix the issue?

It does, see #54.

**Comment by x1m** [comment]
Ok thank you
