### ISSUE TITLE
TypeError: 'ABCMeta' object is not subscriptable when running example

### ISSUE THREAD

**Issue by jwalters-gpsw** [vmagamedov/grpclib#86]
TypeError: 'ABCMeta' object is not subscriptable when running helloworld example server.

```
bash-3.2$ python -m helloworld.server
Traceback (most recent call last):
  File "/anaconda3/envs/local-python37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/local-python37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jwalters/tmp/grpclib/examples/helloworld/server.py", line 11, in <module>
    class Greeter(GreeterBase):
  File "/Users/jwalters/tmp/grpclib/examples/helloworld/server.py", line 13, in Greeter
    async def SayHello(self, stream: Stream[HelloRequest, HelloReply]) -> None:
TypeError: 'ABCMeta' object is not subscriptable
bash-3.2$ python -m helloworld.server
Traceback (most recent call last):
  File "/anaconda3/envs/local-python37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/local-python37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jwalters/tmp/grpclib/examples/helloworld/server.py", line 11, in <module>
    class Greeter(GreeterBase):
  File "/Users/jwalters/tmp/grpclib/examples/helloworld/server.py", line 13, in Greeter
    async def SayHello(self, stream: Stream[HelloRequest, HelloReply]) -> None:
TypeError: 'ABCMeta' object is not subscriptable
```
Python version: 3.7.3
Libraries:
```
Package           Version  
----------------- ---------
aiohttp           3.5.4    
appnope           0.1.0    
asn1crypto        0.24.0   
async-timeout     3.0.1    
attrs             19.1.0   
backcall          0.1.0    
certifi           2019.6.16
cffi              1.12.3   
chainmap          1.0.3    
chardet           3.0.4    
combomethod       1.0.12   
cryptography      2.7      
decorator         4.4.0    
defusedxml        0.6.0    
grpclib           0.2.5    
h2                3.1.0    
hpack             3.0.0    
hyperframe        5.2.0    
idna              2.8      
jedi              0.14.1   
multidict         4.5.2    
nulltype          2.3.1    
oauthlib          3.0.2    
options           1.4.10   
parso             0.5.1    
pbr               5.4.1    
pexpect           4.7.0    
pickleshare       0.7.5    
pip               19.1.1   
prompt-toolkit    2.0.9    
protobuf          3.9.0    
ptyprocess        0.6.0    
pycparser         2.19     
Pygments          2.4.2    
PyJWT             1.7.1    
requests          2.22.0   
requests-oauthlib 1.2.0    
requests-toolbelt 0.9.1    
setuptools        41.0.1   
six               1.12.0   
slackclient       2.1.0    
traitlets         4.3.2    
urllib3           1.25.3   
wcwidth           0.1.7    
wheel             0.33.4   
yarl              1.3.0    
```

**Comment by vmagamedov** [comment]
Typing support was added in 0.3.0 version, which still isn't released as a stable version. You can try `grpclib==0.3.0rc5` version or remove typing annotations.

**Comment by jwalters-gpsw** [comment]
Thanks. Will try that.

**Comment by jwalters-gpsw** [comment]
Seems fine now.

**Comment by martinKindall** [comment]
> Typing support was added in 0.3.0 version, which still isn't released as a stable version. You can try `grpclib==0.3.0rc5` version or remove typing annotations.

Yep, removed type annotation and the error was gone in my case. 

Using Python 3.7.4

**Comment by vmagamedov** [comment]
@martinKindall current stable version is `0.3.1`, there are no backward-incompatible changes, it is better to upgrade
