### ISSUE TITLE
Transport implementation is buggy

### ISSUE THREAD

**Issue by fraxinas** [vmagamedov/grpclib#9]
```
$ python3 -m helloworld.server
Serving on 127.0.0.1:50051
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/lib/python3.6/site-packages/grpclib/protocol.py", line 412, in data_received
    self.processor.process(event)
  File "/usr/lib/python3.6/site-packages/grpclib/protocol.py", line 335, in process
    proc(event)
  File "/usr/lib/python3.6/site-packages/grpclib/protocol.py", line 371, in process_stream_reset
    stream = self.streams.pop(event.stream_id)
KeyError: 1
Server error
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/grpclib/server.py", line 137, in request_handler
    await method.func(stream)
  File "/home/fraxinas/Code/grpclib/example/helloworld/server.py", line 14, in SayHello
    await stream.send_message(HelloReply(message=message))
  File "/usr/lib/python3.6/site-packages/grpclib/server.py", line 48, in send_message
    await self.send_initial_metadata()
  File "/usr/lib/python3.6/site-packages/grpclib/server.py", line 43, in send_initial_metadata
    ('content-type', CONTENT_TYPE)])
  File "/usr/lib/python3.6/site-packages/grpclib/protocol.py", line 231, in send_headers
    end_stream=end_stream)
  File "/usr/lib/python3.6/site-packages/h2/connection.py", line 766, in send_headers
    headers, self.encoder, end_stream
  File "/usr/lib/python3.6/site-packages/h2/stream.py", line 895, in send_headers
    events = self.state_machine.process_input(input_)
  File "/usr/lib/python3.6/site-packages/h2/stream.py", line 129, in process_input
    return func(self, previous_state)
  File "/usr/lib/python3.6/site-packages/h2/stream.py", line 348, in send_on_closed_stream
    raise StreamClosedError(self.stream_id)
h2.exceptions.StreamClosedError: 1
```

```
$ python3 -m helloworld.client
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fraxinas/Code/grpclib/example/helloworld/client.py", line 17, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/fraxinas/Code/grpclib/example/helloworld/client.py", line 13, in main
    print(await stub.SayHello(HelloRequest(name='World')))
  File "/usr/lib/python3.6/site-packages/grpclib/client.py", line 234, in __call__
    return await stream.recv_message()
  File "/usr/lib/python3.6/site-packages/grpclib/client.py", line 117, in recv_message
    await self.recv_initial_metadata()
  File "/usr/lib/python3.6/site-packages/grpclib/client.py", line 95, in recv_initial_metadata
    async with self._with_deadline():
AttributeError: __aexit__
``` 
with master https://github.com/vmagamedov/grpclib/commit/d523b60cbe52bdfc8f5b30e7a3223906b91d6cc9 and
```
$ python -V
Python 3.6.2
```

**Comment by vmagamedov** [comment]
The first exception is clear to me, test suite currently doesn't cover all such cases and this is what I'm going to fix in the near future.

And the second exception on the client-side is somewhat strange, `self._with_deadline()` should return `async_timeout.timeout()` object which should have `__aexit__` method. Can you provide more information about how to reproduce this error? Or you just run these examples without any modifications right after checkout and grpclib doesn't work for you at all?

**Comment by fraxinas** [comment]
`Or you just run these examples without any modifications right after checkout and grpclib doesn't work for you at all?` 
that's what i did

**Comment by vmagamedov** [comment]
I've managed to reproduce error on the server, but I need more information to reproduce error on the client.

Please checkout `patch-9` branch:
```
git pull https://github.com/vmagamedov/grpclib.git patch-9
git checkout patch-9
```
and show me output from the client.

Can you also show me your environment?
```
pip3 freeze
```

**Comment by fraxinas** [comment]
```
$ pip3 freeze
aioftp==0.6.1
aiohttp==2.0.7
alabaster==0.7.10
appdirs==1.4.3
asn1crypto==0.23.0
astroid==1.5.3
async-timeout==1.2.0
asyncssh==1.11.0
Babel==2.5.1
Beaker==1.8.1
Brlapi==0.6.6
cached-property==1.3.1
cffi==1.11.2
chardet==3.0.4
colorama==0.3.9
cryptography==2.1.1
Cython==0.27.1
decorator==4.1.2
dill==0.2.7.1
docker==2.5.1
docker-compose==1.16.1
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
docutils==0.14
grpcio==1.6.3
grpcio-tools==1.6.3
grpclib==0.2.0
h2==3.0.1
hpack==3.0.0
hyperframe==5.1.0
idna==2.6
imagesize==0.7.1
isc==2.0
iso8601==0.1.11
isort==4.2.15
Jinja2==2.9.6
jsonschema==2.6.0
lazy-object-proxy==1.3.1
louis==3.3.0
lxml==4.1.0
m3u8==0.3.1
Mako==1.0.7
MarkupSafe==1.0
mccabe==0.6.1
meld==3.18.0
multidict==2.1.4
namcap==3.2.7
packaging==16.8
pika==0.11.0
pluggy==0.5.2
ply==3.10
protobuf==3.4.0
psycopg2==2.7.3.1
py==1.4.34
pyalpm==0.8
pyasn1==0.3.6
pycairo==1.13.3
pycparser==2.18
pydbus==0.6.0
pyelftools==0.24
Pygments==2.2.0
pyinotify==0.9.6
pylint==1.7.4
pyparsing==2.2.0
pytest==3.2.3
python-logstash==0.4.6
pytz==2017.2
PyXB==1.2.5
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
simplejson==3.11.1
six==1.11.0
slip==0.6.4
slip.dbus==0.6.4
snowballstemmer==1.2.1
Sphinx==1.6.4
sphinx-rtd-theme==0.2.4
sphinxcontrib-websupport==1.0.1.dev20170522
SQLAlchemy==1.1.14
team==1.0
termcolor==1.1.0
texttable==1.0.0
urllib3==1.22
virtualenv==15.1.0
websocket-client==0.44.0
Whoosh==2.7.4
wrapt==1.10.11
xdot==0.7
yarl==0.10.0
zope.interface==4.4.3
```

relevant line of the client with extra output from patch-9 (from outer space):
```
  File "/usr/lib/python3.6/site-packages/grpclib/client.py", line 97, in recv_initial_metadata
    print(getattr(tm, '__aexit__'))
AttributeError: 'timeout' object has no attribute '__aexit__'
```

**Comment by anxolerd** [comment]
Hm, I guess, the problem is here:

**FROM pip freeze**:
`async-timeout==1.2.0`

**FROM grpclib's setup.py**:
`async-timeout>=1.3.0`

**Comment by vsel** [comment]
+1

**Comment by fraxinas** [comment]
right, this was apparently caused by the legacy async-timeout package. it didn't update properly because i installed it using sudo. sorry for the fuzz and thanks for the prompt responses!

**Comment by vmagamedov** [comment]
I'd like to leave this issue open, until error on the server-side wouldn't be fixed. It is not critical in any way, but it can confuse users in the future. Proper version of the`async-timeout` library only fixes error on the client-side. And it helped to discover error on the server-side.

**Comment by vmagamedov** [comment]
Seems like this issue is not actual anymore, fixed
